DELIMITER ;

LOCK TABLES `ds` WRITE;
INSERT IGNORE INTO `ds` (`table_name`, `title`, `reorderfield`, `use_history`, `searchfield`, `displayfield`, `sortfield`, `searchany`, `hint`, `overview_tpl`, `sync_table`, `writetable`, `globalsearch`, `listselectionmodel`, `sync_view`, `syncable`, `cssstyle`, `alternativeformxtype`, `read_table`, `class_name`, `special_add_panel`, `existsreal`, `character_set_name`, `read_filter`, `listxtypeprefix`, `phpexporter`, `phpexporterfilename`, `combined`, `default_pagesize`, `allowForm`, `listviewbaseclass`, `showactionbtn`, `modelbaseclass`) VALUES ('view_editor_blg_hdr_#####','Belegeditor (Kopf)','',0,'id','id','id',0,'','','','',0,'cellmodel','',0,'','','','Belegarten','',1,'','','','','',0,100,NULL,'',0,'Tualo.DataSets.model.Basic');
UNLOCK TABLES;
LOCK TABLES `ds_column` WRITE;
INSERT IGNORE INTO `ds_column` (`table_name`, `column_name`, `default_value`, `default_max_value`, `default_min_value`, `update_value`, `is_primary`, `syncable`, `referenced_table`, `referenced_column_name`, `is_nullable`, `is_referenced`, `writeable`, `note`, `data_type`, `column_key`, `column_type`, `character_maximum_length`, `numeric_precision`, `numeric_scale`, `character_set_name`, `privileges`, `existsreal`, `deferedload`, `hint`, `fieldtype`) VALUES ('view_editor_blg_hdr_#####','abschluss',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'bigint','','bigint(20)',NULL,19,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','address',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','','varchar(4000)',4000,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','an_lager',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','archiv',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','bezahlt',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'decimal','','decimal(12,5)',NULL,12,5,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','bookingdate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'date','','date',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','brutto',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'decimal','','decimal(12,5)',NULL,12,5,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','buchungsdatum',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'date','','date',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','buchungskreis',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(10)',10,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','companycode',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','','varchar(10)',10,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','costcenter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','create_timestamp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'time','','timestamp',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','date',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'date','','date',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','datev_export',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','datum',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'date','','date',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','faelligam',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'date','','date',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','gedruckt',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'tinyint','','tinyint(4)',NULL,3,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','gedruckt_am',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'date','','date',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','gegeben',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'decimal','','decimal(12,5)',NULL,12,5,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','geschaeftsstelle',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','hardwareid',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(36)',36,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'bigint','','bigint(20)',NULL,19,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','istoffen',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','layout',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','letzte_zahlung',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','letzte_zahlung_datum',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'date','','date',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','login',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','mahnstufe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','mandatsreferenz',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(50)',50,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','minderung',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'decimal','','decimal(12,5)',NULL,12,5,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','netto',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'decimal','','decimal(12,5)',NULL,12,5,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','offen',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'decimal','','decimal(15,6)',NULL,15,6,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','office',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','payuntildate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'date','','date',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','preisorientierung',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(10)',10,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','provision_brutto',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'decimal','','decimal(12,5)',NULL,12,5,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','provision_netto',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'decimal','','decimal(12,5)',NULL,12,5,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','reference',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','referencenr',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','','varchar(10)',10,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','referenz',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','reporttype',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','','varchar(7)',7,NULL,NULL,'utf8mb3','select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','service_period_start',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'date','','date',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','service_period_stop',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'date','','date',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','skonto_brutto',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'decimal','','decimal(12,5)',NULL,12,5,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','skonto_netto',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'decimal','','decimal(12,5)',NULL,12,5,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','sperre',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','steuer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'decimal','','decimal(12,5)',NULL,12,5,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','steuernummer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(50)',50,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','svkunde',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,0,NULL,'varchar','','varchar(50)',50,NULL,NULL,'utf8mb4','select,insert,update,references',0,NULL,NULL,''),
('view_editor_blg_hdr_#####','svmodel',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,0,NULL,'varchar','','varchar(50)',50,NULL,NULL,'utf8mb4','select,insert,update,references',0,NULL,NULL,''),
('view_editor_blg_hdr_#####','tabellenzusatz',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','vertriebsweg',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(255)',255,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','von_lager',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','warehouse',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','zahlart',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','','varchar(20)',20,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','zbeleg',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'bigint','','bigint(20)',NULL,19,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','zbeleg_zusatz',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','zeit',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'time','','time',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','zeitraum_bis',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'date','','date',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','zeitraum_von',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'date','','date',NULL,NULL,NULL,NULL,'select,insert,update,references',1,NULL,NULL,''),
('view_editor_blg_hdr_#####','zurueck',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'decimal','','decimal(12,5)',NULL,12,5,NULL,'select,insert,update,references',1,NULL,NULL,'');
UNLOCK TABLES;
LOCK TABLES `ds_column_list_label` WRITE;
INSERT IGNORE INTO `ds_column_list_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `editor`, `position`, `summaryrenderer`, `renderer`, `summarytype`, `hidden`, `active`, `filterstore`, `grouped`, `flex`, `direction`, `align`, `listfiltertype`, `hint`) VALUES ('view_editor_blg_hdr_#####','abschluss','DE','abschluss','gridcolumn','',2,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','an_lager','DE','an_lager','gridcolumn','',3,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','archiv','DE','archiv','gridcolumn','',4,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','bezahlt','DE','bezahlt','gridcolumn','',5,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','brutto','DE','brutto','gridcolumn','',6,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','buchungsdatum','DE','buchungsdatum','gridcolumn','',7,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','buchungskreis','DE','buchungskreis','gridcolumn','',8,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','create_timestamp','DE','create_timestamp','gridcolumn','',9,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','datev_export','DE','datev_export','gridcolumn','',10,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','datum','DE','Datum','datecolumn','',1,'','','',0,1,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','faelligam','DE','faelligam','gridcolumn','',11,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','gedruckt','DE','gedruckt','gridcolumn','',12,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','gedruckt_am','DE','gedruckt_am','gridcolumn','',13,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','gegeben','DE','gegeben','gridcolumn','',14,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','geschaeftsstelle','DE','geschaeftsstelle','gridcolumn','',15,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','hardwareid','DE','hardwareid','gridcolumn','',16,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','id','DE','id','gridcolumn','',0,'','','',0,1,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','istoffen','DE','istoffen','gridcolumn','',17,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','layout','DE','layout','gridcolumn','',18,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','letzte_zahlung','DE','letzte_zahlung','gridcolumn','',19,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','letzte_zahlung_datum','DE','letzte_zahlung_datum','gridcolumn','',20,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','login','DE','login','gridcolumn','',21,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','mahnstufe','DE','mahnstufe','gridcolumn','',22,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','mandatsreferenz','DE','mandatsreferenz','gridcolumn','',23,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','minderung','DE','minderung','gridcolumn','',24,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','netto','DE','netto','gridcolumn','',25,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','offen','DE','offen','gridcolumn','',26,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','preisorientierung','DE','preisorientierung','gridcolumn','',27,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','provision_brutto','DE','provision_brutto','gridcolumn','',28,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','provision_netto','DE','provision_netto','gridcolumn','',29,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','referenz','DE','referenz','gridcolumn','',30,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','skonto_brutto','DE','skonto_brutto','gridcolumn','',31,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','skonto_netto','DE','skonto_netto','gridcolumn','',32,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','sperre','DE','sperre','gridcolumn','',33,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','steuer','DE','steuer','gridcolumn','',34,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','steuernummer','DE','steuernummer','gridcolumn','',35,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','svkunde','DE','svkunde','gridcolumn','',36,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','svmodel','DE','svmodel','gridcolumn','',37,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','tabellenzusatz','DE','tabellenzusatz','gridcolumn','',38,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','vertriebsweg','DE','vertriebsweg','gridcolumn','',39,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','von_lager','DE','von_lager','gridcolumn','',40,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','zahlart','DE','zahlart','gridcolumn','',41,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','zbeleg','DE','zbeleg','gridcolumn','',42,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','zbeleg_zusatz','DE','zbeleg_zusatz','gridcolumn','',43,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','zeit','DE','zeit','gridcolumn','',44,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','zeitraum_bis','DE','zeitraum_bis','gridcolumn','',45,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','zeitraum_von','DE','zeitraum_von','gridcolumn','',46,'','','',1,0,'',0,1.00,'','','',''),
('view_editor_blg_hdr_#####','zurueck','DE','zurueck','gridcolumn','',47,'','','',1,0,'',0,1.00,'','','','');
UNLOCK TABLES;
LOCK TABLES `ds_column_form_label` WRITE;
INSERT IGNORE INTO `ds_column_form_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `field_path`, `position`, `hidden`, `active`, `allowempty`, `fieldgroup`, `flex`, `hint`) VALUES ('view_editor_blg_hdr_#####','abschluss','DE','abschluss','displayfield','Allgemein',13,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','address','DE','address','displayfield','Allgemein',14,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','an_lager','DE','an_lager','displayfield','Allgemein',15,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','archiv','DE','archiv','displayfield','Allgemein',16,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','bezahlt','DE','bezahlt','displayfield','Allgemein',17,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','bookingdate','DE','Buchungsdatum','hidden','Allgemein',9,0,1,1,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','brutto','DE','brutto','displayfield','Allgemein',12,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','buchungsdatum','DE','buchungsdatum','displayfield','Allgemein',18,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','buchungskreis','DE','buchungskreis','displayfield','Allgemein',19,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','companycode','DE','companycode','displayfield','Allgemein',20,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','costcenter','DE','Kostenstelle','hidden','Allgemein',1,0,1,1,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','create_timestamp','DE','create_timestamp','displayfield','Allgemein',21,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','date','DE','Datum','datefield','Allgemein',4,0,1,0,'Datum',1.00,'\'\''),
('view_editor_blg_hdr_#####','datev_export','DE','datev_export','displayfield','Allgemein',22,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','datum','DE','Datum','datefield','Allgemein',11,1,0,0,'Datum',1.00,'\'\''),
('view_editor_blg_hdr_#####','faelligam','DE','Fällig am','datefield','Allgemein',23,1,0,0,'Datum',1.00,'\'\''),
('view_editor_blg_hdr_#####','gedruckt','DE','gedruckt','displayfield','Allgemein',24,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','gedruckt_am','DE','gedruckt_am','displayfield','Allgemein',25,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','gegeben','DE','gegeben','displayfield','Allgemein',26,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','geschaeftsstelle','DE','geschaeftsstelle','displayfield','Allgemein',27,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','hardwareid','DE','hardwareid','displayfield','Allgemein',28,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','id','DE','Belegnummer','displayfield','Allgemein',3,0,1,1,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','istoffen','DE','istoffen','displayfield','Allgemein',29,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','layout','DE','layout','displayfield','Allgemein',30,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','letzte_zahlung','DE','letzte_zahlung','displayfield','Allgemein',31,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','letzte_zahlung_datum','DE','letzte_zahlung_datum','displayfield','Allgemein',32,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','login','DE','login','displayfield','Allgemein',33,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','mahnstufe','DE','mahnstufe','displayfield','Allgemein',34,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','mandatsreferenz','DE','mandatsreferenz','displayfield','Allgemein',35,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','minderung','DE','minderung','displayfield','Allgemein',36,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','netto','DE','netto','displayfield','Allgemein',37,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','offen','DE','offen','displayfield','Allgemein',39,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','office','DE','office','hidden','Allgemein',2,0,1,1,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','payuntildate','DE','Fällig','datefield','Allgemein',5,0,1,0,'Datum',1.00,'\'\''),
('view_editor_blg_hdr_#####','preisorientierung','DE','preisorientierung','displayfield','Allgemein',40,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','provision_brutto','DE','provision_brutto','displayfield','Allgemein',42,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','provision_netto','DE','provision_netto','displayfield','Allgemein',43,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','reference','DE','Referenz','textfield','Allgemein',8,0,1,1,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','referencenr','DE','Bezug','combobox_view_editor_relation_#####_id','Allgemein',0,0,1,1,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','referenz','DE','referenz','displayfield','Allgemein',44,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','reporttype','DE','Belegart','hidden','Allgemein',10,0,1,1,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','service_period_start','DE','Von','datefield','Allgemein',6,0,1,0,'Leistungszeitraum',1.00,'\'\''),
('view_editor_blg_hdr_#####','service_period_stop','DE','Bis','datefield','Allgemein',7,0,1,0,'Leistungszeitraum',1.00,'\'\''),
('view_editor_blg_hdr_#####','skonto_brutto','DE','skonto_brutto','displayfield','Allgemein',45,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','skonto_netto','DE','skonto_netto','displayfield','Allgemein',46,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','sperre','DE','sperre','displayfield','Allgemein',47,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','steuer','DE','steuer','displayfield','Allgemein',48,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','steuernummer','DE','steuernummer','displayfield','Allgemein',49,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','svkunde','DE','svkunde','displayfield','Allgemein',38,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','svmodel','DE','svmodel','displayfield','Allgemein',41,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','tabellenzusatz','DE','tabellenzusatz','displayfield','Allgemein',50,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','vertriebsweg','DE','vertriebsweg','displayfield','Allgemein',51,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','von_lager','DE','von_lager','displayfield','Allgemein',52,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','warehouse','DE','warehouse','displayfield','Allgemein',53,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','zahlart','DE','zahlart','displayfield','Allgemein',54,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','zbeleg','DE','zbeleg','displayfield','Allgemein',55,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','zbeleg_zusatz','DE','zbeleg_zusatz','displayfield','Allgemein',56,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','zeit','DE','zeit','displayfield','Allgemein',57,1,0,0,'1',1.00,'\'\''),
('view_editor_blg_hdr_#####','zeitraum_bis','DE','Bis','datefield','Allgemein',58,1,0,0,'Leistungszeitraum',1.00,'\'\''),
('view_editor_blg_hdr_#####','zeitraum_von','DE','Von','datefield','Allgemein',59,1,0,0,'Leistungszeitraum',1.00,'\'\''),
('view_editor_blg_hdr_#####','zurueck','DE','zurueck','displayfield','Allgemein',60,1,0,0,'1',1.00,'\'\'');
UNLOCK TABLES;
LOCK TABLES `ds_dropdownfields` WRITE;
UNLOCK TABLES;
LOCK TABLES `ds_reference_tables` WRITE;
UNLOCK TABLES;
LOCK TABLES `ds_addcommands` WRITE;
UNLOCK TABLES;
LOCK TABLES `ds_access` WRITE;
INSERT IGNORE INTO `ds_access` (`role`, `table_name`, `read`, `write`, `delete`, `append`, `existsreal`) VALUES ('administration','view_editor_blg_hdr_#####',1,0,0,0,0);
UNLOCK TABLES;
